version: '3.8'

services:
  # Rust backend application with compute-intensive endpoints
  backend:
    build:
      context: ./backend/rust-backend
      dockerfile: Dockerfile
    networks:
      - benchmark-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - benchmark-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M

  # Caddy reverse proxy
  caddy:
    image: caddy:alpine
    ports:
      - "8081:80"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      backend:
        condition: service_healthy
    command: sh -c "sleep 2 && caddy run --config /etc/caddy/Caddyfile"
    networks:
      - benchmark-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M

  # Traefik reverse proxy
  traefik:
    image: traefik:v2.10
    ports:
      - "8082:80"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--api.insecure=false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - benchmark-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M

  # HAProxy reverse proxy
  haproxy:
    image: haproxy:alpine
    ports:
      - "8083:80"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - benchmark-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M

networks:
  benchmark-network:
    driver: bridge
