http:
  routers:
    backend-router:
      rule: "PathPrefix(`/`)"
      service: backend-service
      entryPoints:
        - web
      middlewares:
        - compression

  services:
    backend-service:
      loadBalancer:
        servers:
          - url: "http://backend:3000"
        # Keepalive settings similar to nginx
        passHostHeader: true
        responseForwarding:
          flushInterval: 0ms
        healthCheck:
          interval: 30s
          timeout: 5s
          path: /
          
  middlewares:
    compression:
      compress:
        excludedContentTypes:
          - "text/event-stream"

  # Configure transport settings for better performance
  serversTransports:
    default:
      maxIdleConnsPerHost: 128
      forwardingTimeouts:
        dialTimeout: 2s
        responseHeaderTimeout: 0s
        idleConnTimeout: 65s
